INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Afghanistan', 'AF', 'AFG', 4, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Albania', 'AL', 'ALB', 8, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Algeria', 'DZ', 'DZA', 12, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('American Samoa', 'AS', 'ASM', 16, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Andorra', 'AD', 'AND', 20, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Angola', 'AO', 'AGO', 24, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Anguilla', 'AI', 'AIA', 660, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Antarctica', 'AQ', 'ATA', 10, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Antigua and Barbuda', 'AG', 'ATG', 28, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Argentina', 'AR', 'ARG', 32, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Armenia', 'AM', 'ARM', 51, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Aruba', 'AW', 'ABW', 533, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Australia', 'AU', 'AUS', 36, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Austria', 'AT', 'AUT', 40, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Azerbaijan', 'AZ', 'AZE', 31, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bahamas', 'BS', 'BHS', 44, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bahrain', 'BH', 'BHR', 48, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bangladesh', 'BD', 'BGD', 50, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Barbados', 'BB', 'BRB', 52, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Belarus', 'BY', 'BLR', 112, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Belgium', 'BE', 'BEL', 56, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Belize', 'BZ', 'BLZ', 84, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Benin', 'BJ', 'BEN', 204, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bermuda', 'BM', 'BMU', 60, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bhutan', 'BT', 'BTN', 64, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Botswana', 'BW', 'BWA', 72, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bouvet Island', 'BV', 'BVT', 74, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Brazil', 'BR', 'BRA', 76, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('British Indian Ocean Territory', 'IO', 'IOT', 86, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Brunei Darussalam', 'BN', 'BRN', 96, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Bulgaria', 'BG', 'BGR', 100, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Burkina Faso', 'BF', 'BFA', 854, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Burundi', 'BI', 'BDI', 108, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cambodia', 'KH', 'KHM', 116, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cameroon', 'CM', 'CMR', 120, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Canada', 'CA', 'CAN', 124, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cape Verde', 'CV', 'CPV', 132, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cayman Islands', 'KY', 'CYM', 136, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Central African Republic', 'CF', 'CAF', 140, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Chad', 'TD', 'TCD', 148, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Chile', 'CL', 'CHL', 152, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('China', 'CN', 'CHN', 156, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Christmas Island', 'CX', 'CXR', 162, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cocos (Keeling) Islands', 'CC', 'CCK', 166, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Colombia', 'CO', 'COL', 170, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Comoros', 'KM', 'COM', 174, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Congo', 'CG', 'COG', 178, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cook Islands', 'CK', 'COK', 184, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Costa Rica', 'CR', 'CRI', 188, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cuba', 'CU', 'CUB', 192, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Cyprus', 'CY', 'CYP', 196, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Czech Republic', 'CZ', 'CZE', 203, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Denmark', 'DK', 'DNK', 208, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Djibouti', 'DJ', 'DJI', 262, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Dominica', 'DM', 'DMA', 212, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Dominican Republic', 'DO', 'DOM', 214, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Ecuador', 'EC', 'ECU', 218, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Egypt', 'EG', 'EGY', 818, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('El Salvador', 'SV', 'SLV', 222, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Equatorial Guinea', 'GQ', 'GNQ', 226, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Eritrea', 'ER', 'ERI', 232, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Estonia', 'EE', 'EST', 233, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Ethiopia', 'ET', 'ETH', 231, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Faroe Islands', 'FO', 'FRO', 234, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Fiji', 'FJ', 'FJI', 242, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Finland', 'FI', 'FIN', 246, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('France', 'FR', 'FRA', 250, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('French Guiana', 'GF', 'GUF', 254, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('French Polynesia', 'PF', 'PYF', 258, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('French Southern Territories', 'TF', 'ATF', 260, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Gabon', 'GA', 'GAB', 266, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Gambia', 'GM', 'GMB', 270, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Georgia', 'GE', 'GEO', 268, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Germany', 'DE', 'DEU', 276, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Ghana', 'GH', 'GHA', 288, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Gibraltar', 'GI', 'GIB', 292, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Greece', 'GR', 'GRC', 300, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Greenland', 'GL', 'GRL', 304, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Grenada', 'GD', 'GRD', 308, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Guadeloupe', 'GP', 'GLP', 312, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Guam', 'GU', 'GUM', 316, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Guatemala', 'GT', 'GTM', 320, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Guinea', 'GN', 'GIN', 324, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Guinea-Bissau', 'GW', 'GNB', 624, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Guyana', 'GY', 'GUY', 328, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Haiti', 'HT', 'HTI', 332, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Holy See (Vatican City State)', 'VA', 'VAT', 336, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Honduras', 'HN', 'HND', 340, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Hong Kong', 'HK', 'HKG', 344, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Hungary', 'HU', 'HUN', 348, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Iceland', 'IS', 'ISL', 352, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('India', 'IN', 'IND', 356, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Indonesia', 'ID', 'IDN', 360, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Iraq', 'IQ', 'IRQ', 368, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Ireland', 'IE', 'IRL', 372, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Israel', 'IL', 'ISR', 376, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Italy', 'IT', 'ITA', 380, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Jamaica', 'JM', 'JAM', 388, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Japan', 'JP', 'JPN', 392, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Jordan', 'JO', 'JOR', 400, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Kazakhstan', 'KZ', 'KAZ', 398, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Kenya', 'KE', 'KEN', 404, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Kiribati', 'KI', 'KIR', 296, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Korea, Republic of', 'KR', 'KOR', 410, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Kuwait', 'KW', 'KWT', 414, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Kyrgyzstan', 'KG', 'KGZ', 417, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Latvia', 'LV', 'LVA', 428, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Lebanon', 'LB', 'LBN', 422, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Lesotho', 'LS', 'LSO', 426, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Liberia', 'LR', 'LBR', 430, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Libyan Arab Jamahiriya', 'LY', 'LBY', 434, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Liechtenstein', 'LI', 'LIE', 438, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Lithuania', 'LT', 'LTU', 440, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Luxembourg', 'LU', 'LUX', 442, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Madagascar', 'MG', 'MDG', 450, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Malawi', 'MW', 'MWI', 454, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Malaysia', 'MY', 'MYS', 458, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Maldives', 'MV', 'MDV', 462, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mali', 'ML', 'MLI', 466, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Malta', 'MT', 'MLT', 470, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Marshall Islands', 'MH', 'MHL', 584, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Martinique', 'MQ', 'MTQ', 474, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mauritania', 'MR', 'MRT', 478, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mauritius', 'MU', 'MUS', 480, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mayotte', 'YT', 'MYT', 175, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mexico', 'MX', 'MEX', 484, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Micronesia, Federated States of', 'FM', 'FSM', 583, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Moldova, Republic of', 'MD', 'MDA', 498, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Monaco', 'MC', 'MCO', 492, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mongolia', 'MN', 'MNG', 496, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Montenegro', 'ME', 'MNE', 499, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Montserrat', 'MS', 'MSR', 500, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Morocco', 'MA', 'MAR', 504, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Mozambique', 'MZ', 'MOZ', 508, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Namibia', 'NA', 'NAM', 516, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Nauru', 'NR', 'NRU', 520, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Nepal', 'NP', 'NPL', 524, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Netherlands', 'NL', 'NLD', 528, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Netherlands Antilles', 'AN', 'ANT', 530, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('New Caledonia', 'NC', 'NCL', 540, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('New Zealand', 'NZ', 'NZL', 554, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Nicaragua', 'NI', 'NIC', 558, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Niger', 'NE', 'NER', 562, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Nigeria', 'NG', 'NGA', 566, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Niue', 'NU', 'NIU', 570, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Norfolk Island', 'NF', 'NFK', 574, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Northern Mariana Islands', 'MP', 'MNP', 580, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Norway', 'NO', 'NOR', 578, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Oman', 'OM', 'OMN', 512, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Pakistan', 'PK', 'PAK', 586, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Palau', 'PW', 'PLW', 585, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Panama', 'PA', 'PAN', 591, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Papua New Guinea', 'PG', 'PNG', 598, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Paraguay', 'PY', 'PRY', 600, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Peru', 'PE', 'PER', 604, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Philippines', 'PH', 'PHL', 608, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Pitcairn', 'PN', 'PCN', 612, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Poland', 'PL', 'POL', 616, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Portugal', 'PT', 'PRT', 620, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Puerto Rico', 'PR', 'PRI', 630, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Qatar', 'QA', 'QAT', 634, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Reunion', 'RE', 'REU', 638, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Romania', 'RO', 'ROU', 642, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Russian Federation', 'RU', 'RUS', 643, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Rwanda', 'RW', 'RWA', 646, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Saint Kitts and Nevis', 'KN', 'KNA', 659, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Saint Lucia', 'LC', 'LCA', 662, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Samoa', 'WS', 'WSM', 882, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('San Marino', 'SM', 'SMR', 674, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Sao Tome and Principe', 'ST', 'STP', 678, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Saudi Arabia', 'SA', 'SAU', 682, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Senegal', 'SN', 'SEN', 686, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Serbia', 'RS', 'SRB', 688, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Seychelles', 'SC', 'SYC', 690, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Sierra Leone', 'SL', 'SLE', 694, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Singapore', 'SG', 'SGP', 702, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Slovenia', 'SI', 'SVN', 705, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Solomon Islands', 'SB', 'SLB', 90, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Somalia', 'SO', 'SOM', 706, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('South Africa', 'ZA', 'ZAF', 710, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Spain', 'ES', 'ESP', 724, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Sri Lanka', 'LK', 'LKA', 144, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Sudan', 'SD', 'SDN', 736, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Suriname', 'SR', 'SUR', 740, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Swaziland', 'SZ', 'SWZ', 748, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Sweden', 'SE', 'SWE', 752, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Switzerland', 'CH', 'CHE', 756, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Syrian Arab Republic', 'SY', 'SYR', 760, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Taiwan, Province of China', 'TW', 'TWN', 158, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Tajikistan', 'TJ', 'TJK', 762, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Tanzania, United Republic of', 'TZ', 'TZA', 834, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Thailand', 'TH', 'THA', 764, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Togo', 'TG', 'TGO', 768, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Tokelau', 'TK', 'TKL', 772, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Tonga', 'TO', 'TON', 776, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Trinidad and Tobago', 'TT', 'TTO', 780, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Tunisia', 'TN', 'TUN', 788, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Turkey', 'TR', 'TUR', 792, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Turkmenistan', 'TM', 'TKM', 795, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Turks and Caicos Islands', 'TC', 'TCA', 796, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Tuvalu', 'TV', 'TUV', 798, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Uganda', 'UG', 'UGA', 800, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Ukraine', 'UA', 'UKR', 804, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('United Arab Emirates', 'AE', 'ARE', 784, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('United Kingdom', 'GB', 'GBR', 826, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('United States', 'US', 'USA', 840, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Uruguay', 'UY', 'URY', 858, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Uzbekistan', 'UZ', 'UZB', 860, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Vanuatu', 'VU', 'VUT', 548, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Viet Nam', 'VN', 'VNM', 704, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Western Sahara', 'EH', 'ESH', 732, false)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Yemen', 'YE', 'YEM', 887, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Zambia', 'ZM', 'ZMB', 894, true )
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number, Compliant) values ('Zimbabwe', 'ZW', 'ZWE', 716, false)
