INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Afghanistan', 'AF', 'AFG', 4)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Aland Islands', 'AX', 'ALA', 248)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Albania', 'AL', 'ALB', 8)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Algeria', 'DZ', 'DZA', 12)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('American Samoa', 'AS', 'ASM', 16)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Andorra', 'AD', 'AND', 20)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Angola', 'AO', 'AGO', 24)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Anguilla', 'AI', 'AIA', 660)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Antarctica', 'AQ', 'ATA', 10)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Antigua and Barbuda', 'AG', 'ATG', 28)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Argentina', 'AR', 'ARG', 32)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Armenia', 'AM', 'ARM', 51)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Aruba', 'AW', 'ABW', 533)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Australia', 'AU', 'AUS', 36)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Austria', 'AT', 'AUT', 40)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Azerbaijan', 'AZ', 'AZE', 31)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bahamas', 'BS', 'BHS', 44)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bahrain', 'BH', 'BHR', 48)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bangladesh', 'BD', 'BGD', 50)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Barbados', 'BB', 'BRB', 52)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Belarus', 'BY', 'BLR', 112)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Belgium', 'BE', 'BEL', 56)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Belize', 'BZ', 'BLZ', 84)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Benin', 'BJ', 'BEN', 204)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bermuda', 'BM', 'BMU', 60)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bhutan', 'BT', 'BTN', 64)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bolivia, Plurinational State of', 'BO', 'BOL', 68)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bosnia and Herzegovina', 'BA', 'BIH', 70)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Botswana', 'BW', 'BWA', 72)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bouvet Island', 'BV', 'BVT', 74)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Brazil', 'BR', 'BRA', 76)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('British Indian Ocean Territory', 'IO', 'IOT', 86)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Brunei Darussalam', 'BN', 'BRN', 96)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Bulgaria', 'BG', 'BGR', 100)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Burkina Faso', 'BF', 'BFA', 854)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Burundi', 'BI', 'BDI', 108)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cambodia', 'KH', 'KHM', 116)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cameroon', 'CM', 'CMR', 120)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Canada', 'CA', 'CAN', 124)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cape Verde', 'CV', 'CPV', 132)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cayman Islands', 'KY', 'CYM', 136)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Central African Republic', 'CF', 'CAF', 140)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Chad', 'TD', 'TCD', 148)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Chile', 'CL', 'CHL', 152)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('China', 'CN', 'CHN', 156)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Christmas Island', 'CX', 'CXR', 162)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cocos (Keeling) Islands', 'CC', 'CCK', 166)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Colombia', 'CO', 'COL', 170)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Comoros', 'KM', 'COM', 174)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Congo', 'CG', 'COG', 178)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Congo, Democratic Republic of the', 'CD', 'COD', 180)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cook Islands', 'CK', 'COK', 184)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Costa Rica', 'CR', 'CRI', 188)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cote d''Ivoire', 'CI', 'CIV', 384)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Croatia', 'HR', 'HRV', 191)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cuba', 'CU', 'CUB', 192)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Cyprus', 'CY', 'CYP', 196)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Czech Republic', 'CZ', 'CZE', 203)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Denmark', 'DK', 'DNK', 208)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Djibouti', 'DJ', 'DJI', 262)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Dominica', 'DM', 'DMA', 212)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Dominican Republic', 'DO', 'DOM', 214)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Ecuador', 'EC', 'ECU', 218)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Egypt', 'EG', 'EGY', 818)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('El Salvador', 'SV', 'SLV', 222)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Equatorial Guinea', 'GQ', 'GNQ', 226)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Eritrea', 'ER', 'ERI', 232)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Estonia', 'EE', 'EST', 233)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Ethiopia', 'ET', 'ETH', 231)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Faroe Islands', 'FO', 'FRO', 234)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Fiji', 'FJ', 'FJI', 242)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Finland', 'FI', 'FIN', 246)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('France', 'FR', 'FRA', 250)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('French Guiana', 'GF', 'GUF', 254)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('French Polynesia', 'PF', 'PYF', 258)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('French Southern Territories', 'TF', 'ATF', 260)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Gabon', 'GA', 'GAB', 266)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Gambia', 'GM', 'GMB', 270)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Georgia', 'GE', 'GEO', 268)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Germany', 'DE', 'DEU', 276)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Ghana', 'GH', 'GHA', 288)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Gibraltar', 'GI', 'GIB', 292)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Greece', 'GR', 'GRC', 300)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Greenland', 'GL', 'GRL', 304)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Grenada', 'GD', 'GRD', 308)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guadeloupe', 'GP', 'GLP', 312)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guam', 'GU', 'GUM', 316)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guatemala', 'GT', 'GTM', 320)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guernsey', 'GG', 'GGY', 831)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guinea', 'GN', 'GIN', 324)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guinea-Bissau', 'GW', 'GNB', 624)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Guyana', 'GY', 'GUY', 328)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Haiti', 'HT', 'HTI', 332)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Heard Island and McDonald Islands', 'HM', 'HMD', 334)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Holy See (Vatican City State)', 'VA', 'VAT', 336)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Honduras', 'HN', 'HND', 340)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Hong Kong', 'HK', 'HKG', 344)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Hungary', 'HU', 'HUN', 348)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Iceland', 'IS', 'ISL', 352)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('India', 'IN', 'IND', 356)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Indonesia', 'ID', 'IDN', 360)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Iran, Islamic Republic of', 'IR', 'IRN', 364)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Iraq', 'IQ', 'IRQ', 368)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Ireland', 'IE', 'IRL', 372)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Isle of Man', 'IM', 'IMN', 833)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Israel', 'IL', 'ISR', 376)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Italy', 'IT', 'ITA', 380)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Jamaica', 'JM', 'JAM', 388)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Japan', 'JP', 'JPN', 392)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Jersey', 'JE', 'JEY', 832)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Jordan', 'JO', 'JOR', 400)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Kazakhstan', 'KZ', 'KAZ', 398)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Kenya', 'KE', 'KEN', 404)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Kiribati', 'KI', 'KIR', 296)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 408)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Korea, Republic of', 'KR', 'KOR', 410)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Kuwait', 'KW', 'KWT', 414)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Kyrgyzstan', 'KG', 'KGZ', 417)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Lao People''s Democratic Republic', 'LA', 'LAO', 418)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Latvia', 'LV', 'LVA', 428)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Lebanon', 'LB', 'LBN', 422)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Lesotho', 'LS', 'LSO', 426)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Liberia', 'LR', 'LBR', 430)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Libyan Arab Jamahiriya', 'LY', 'LBY', 434)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Liechtenstein', 'LI', 'LIE', 438)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Lithuania', 'LT', 'LTU', 440)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Luxembourg', 'LU', 'LUX', 442)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Macao', 'MO', 'MAC', 446)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Macedonia, the former Yugoslav Republic of', 'MK', 'MKD', 807)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Madagascar', 'MG', 'MDG', 450)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Malawi', 'MW', 'MWI', 454)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Malaysia', 'MY', 'MYS', 458)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Maldives', 'MV', 'MDV', 462)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mali', 'ML', 'MLI', 466)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Malta', 'MT', 'MLT', 470)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Marshall Islands', 'MH', 'MHL', 584)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Martinique', 'MQ', 'MTQ', 474)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mauritania', 'MR', 'MRT', 478)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mauritius', 'MU', 'MUS', 480)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mayotte', 'YT', 'MYT', 175)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mexico', 'MX', 'MEX', 484)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Micronesia, Federated States of', 'FM', 'FSM', 583)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Moldova, Republic of', 'MD', 'MDA', 498)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Monaco', 'MC', 'MCO', 492)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mongolia', 'MN', 'MNG', 496)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Montenegro', 'ME', 'MNE', 499)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Montserrat', 'MS', 'MSR', 500)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Morocco', 'MA', 'MAR', 504)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Mozambique', 'MZ', 'MOZ', 508)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Myanmar', 'MM', 'MMR', 104)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Namibia', 'NA', 'NAM', 516)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Nauru', 'NR', 'NRU', 520)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Nepal', 'NP', 'NPL', 524)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Netherlands', 'NL', 'NLD', 528)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Netherlands Antilles', 'AN', 'ANT', 530)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('New Caledonia', 'NC', 'NCL', 540)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('New Zealand', 'NZ', 'NZL', 554)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Nicaragua', 'NI', 'NIC', 558)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Niger', 'NE', 'NER', 562)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Nigeria', 'NG', 'NGA', 566)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Niue', 'NU', 'NIU', 570)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Norfolk Island', 'NF', 'NFK', 574)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Northern Mariana Islands', 'MP', 'MNP', 580)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Norway', 'NO', 'NOR', 578)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Oman', 'OM', 'OMN', 512)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Pakistan', 'PK', 'PAK', 586)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Palau', 'PW', 'PLW', 585)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Palestinian Territory, Occupied', 'PS', 'PSE', 275)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Panama', 'PA', 'PAN', 591)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Papua New Guinea', 'PG', 'PNG', 598)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Paraguay', 'PY', 'PRY', 600)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Peru', 'PE', 'PER', 604)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Philippines', 'PH', 'PHL', 608)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Pitcairn', 'PN', 'PCN', 612)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Poland', 'PL', 'POL', 616)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Portugal', 'PT', 'PRT', 620)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Puerto Rico', 'PR', 'PRI', 630)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Qatar', 'QA', 'QAT', 634)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Reunion', 'RE', 'REU', 638)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Romania', 'RO', 'ROU', 642)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Russian Federation', 'RU', 'RUS', 643)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Rwanda', 'RW', 'RWA', 646)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Barthelemy', 'BL', 'BLM', 652)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Helena', 'SH', 'SHN', 654)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Kitts and Nevis', 'KN', 'KNA', 659)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Lucia', 'LC', 'LCA', 662)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Martin (French part)', 'MF', 'MAF', 663)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Pierre and Miquelon', 'PM', 'SPM', 666)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Samoa', 'WS', 'WSM', 882)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('San Marino', 'SM', 'SMR', 674)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Sao Tome and Principe', 'ST', 'STP', 678)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Saudi Arabia', 'SA', 'SAU', 682)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Senegal', 'SN', 'SEN', 686)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Serbia', 'RS', 'SRB', 688)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Seychelles', 'SC', 'SYC', 690)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Sierra Leone', 'SL', 'SLE', 694)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Singapore', 'SG', 'SGP', 702)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Slovakia', 'SK', 'SVK', 703)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Slovenia', 'SI', 'SVN', 705)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Solomon Islands', 'SB', 'SLB', 90)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Somalia', 'SO', 'SOM', 706)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('South Africa', 'ZA', 'ZAF', 710)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Spain', 'ES', 'ESP', 724)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Sri Lanka', 'LK', 'LKA', 144)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Sudan', 'SD', 'SDN', 736)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Suriname', 'SR', 'SUR', 740)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Swaziland', 'SZ', 'SWZ', 748)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Sweden', 'SE', 'SWE', 752)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Switzerland', 'CH', 'CHE', 756)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Syrian Arab Republic', 'SY', 'SYR', 760)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Taiwan, Province of China', 'TW', 'TWN', 158)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Tajikistan', 'TJ', 'TJK', 762)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Tanzania, United Republic of', 'TZ', 'TZA', 834)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Thailand', 'TH', 'THA', 764)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Timor-Leste', 'TL', 'TLS', 626)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Togo', 'TG', 'TGO', 768)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Tokelau', 'TK', 'TKL', 772)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Tonga', 'TO', 'TON', 776)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Trinidad and Tobago', 'TT', 'TTO', 780)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Tunisia', 'TN', 'TUN', 788)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Turkey', 'TR', 'TUR', 792)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Turkmenistan', 'TM', 'TKM', 795)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Turks and Caicos Islands', 'TC', 'TCA', 796)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Tuvalu', 'TV', 'TUV', 798)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Uganda', 'UG', 'UGA', 800)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Ukraine', 'UA', 'UKR', 804)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('United Arab Emirates', 'AE', 'ARE', 784)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('United Kingdom', 'GB', 'GBR', 826)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('United States', 'US', 'USA', 840)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('United States Minor Outlying Islands', 'UM', 'UMI', 581)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Uruguay', 'UY', 'URY', 858)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Uzbekistan', 'UZ', 'UZB', 860)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Vanuatu', 'VU', 'VUT', 548)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Venezuela, Bolivarian Republic of', 'VE', 'VEN', 862)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Viet Nam', 'VN', 'VNM', 704)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Virgin Islands, British', 'VG', 'VGB', 92)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Virgin Islands, U.S.', 'VI', 'VIR', 850)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Wallis and Futuna', 'WF', 'WLF', 876)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Western Sahara', 'EH', 'ESH', 732)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Yemen', 'YE', 'YEM', 887)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Zambia', 'ZM', 'ZMB', 894)
INSERT CountryOfOrigin (Name, Bigram, Trigram, Number) values ('Zimbabwe', 'ZW', 'ZWE', 716)